name: Test Action

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: |
            mkdir -p build
            go build -v -o ./build/webapp ./...
      - name: Test with the Go CLI
        run: go test

      - name: Packer setup
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: latest

      - name: Packer init
        id: init
        run: "packer init ./packer.pkr.hcl"

      - name: Packer validation
        id: validate
        run: |
          if ! packer validate ./packer.pkr.hcl ; then
            echo "Validation failure"
            exit 1
          fi

      - name: Packer fmt
        id: fmt
        run: |
          if ! packer fmt -check ./packer.pkr.hcl ; then
            echo "Formatting failure"
            exit 1
          fi

      - run: echo "Check successful"
