name: learn-github-actions
on:
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    name: go-action
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - run: echo "Check successful"
